In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/B SAGAR KUMAR/OneDrive/Desktop/archive/netflix_titles/netflix.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [2]:
import numpy as np
raw=df.copy()
print(df.shape)

(8807, 12)

In [3]:
df.info()
miss = df.isna().sum()
print(pd.DataFrame({"missing": miss, "pct": (miss/len(df)*100).round(1)}))
print(df.duplicated().sum(), df["show_id"].duplicated().sum())
print(df["rating"].value_counts())

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB
              missing   pct
show_id             0   0.0
type                0   0.0
title               0   0.0
director         2634  29.9
cast              825   9.4
country           831   9.4
date_added         10   0.1
release_year        0   0.0
rating              4   0.0
duration            3   0.0
listed_in           0   0.0
description         0   0.0
0 0
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [4]:
shifted = df["rating"].str.contains("min", na=False)
df.loc[shifted, "duration"] = df.loc[shifted, "rating"]
df.loc[shifted, "rating"] = np.nan

In [5]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
df.info()
miss = df.isna().sum()
print(pd.DataFrame({"missing": miss, "pct": (miss/len(df)*100).round(1)}))
print(df.duplicated().sum(), df["show_id"].duplicated().sum())
print(df["rating"].value_counts())

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8800 non-null   str
 9   duration      8807 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB
              missing   pct
show_id             0   0.0
type                0   0.0
title               0   0.0
director         2634  29.9
cast              825   9.4
country           831   9.4
date_added         10   0.1
release_year        0   0.0
rating              7   0.1
duration            0   0.0
listed_in           0   0.0
description         0   0.0
0 0
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [7]:
shifted = df["rating"].str.contains("min", na=False)
df.loc[shifted, "duration"] = df.loc[shifted, "rating"]
df.loc[shifted, "rating"] = np.nan

In [8]:
# strip stray whitespace in every text column
for c in df.select_dtypes(include=["object", "string"]).columns:
    df[c] = df[c].str.strip()

# 7 country strings have stray commas (e.g. "Germany, ") -> clean them
df["country"] = df["country"].str.split(",").apply(
    lambda xs: ", ".join(x.strip() for x in xs if x.strip()) if isinstance(xs, list) else np.nan
).replace("", np.nan)

In [9]:
for c in ["director", "cast", "country"]:
    df[f"{c}_missing"] = df[c].isna().astype(int)   # keep the missingness as a feature
    df[c] = df[c].fillna("Unknown")

In [10]:
df["date_added"] = pd.to_datetime(df["date_added"], format="%B %d, %Y", errors="coerce")
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month

In [11]:
dur = df["duration"].str.extract(r"(\d+)\s*(\w+)")
df["duration_value"] = dur[0].astype(float)
df["duration_unit"] = dur[1].str.replace("Seasons", "Season")
df["runtime_min"] = np.where(df["duration_unit"] == "min", df["duration_value"], np.nan)
df["n_seasons"]   = np.where(df["duration_unit"] == "Season", df["duration_value"], np.nan)

In [12]:
df["years_to_netflix"] = df["year_added"] - df["release_year"]
df["n_genres"]     = df["listed_in"].str.split(", ").str.len()
df["n_countries"]  = np.where(df["country"] == "Unknown", 0, df["country"].str.split(", ").str.len())
df["cast_size"]    = np.where(df["cast"] == "Unknown", 0, df["cast"].str.split(", ").str.len())
df["description_length"] = df["description"].str.split().str.len()
df["primary_country"] = df["country"].str.split(", ").str[0]

In [13]:
m = {"TV-Y":"Kids","TV-Y7":"Kids","TV-Y7-FV":"Kids","TV-G":"Kids","G":"Kids",
     "TV-PG":"Teens","PG":"Teens","TV-14":"Teens","PG-13":"Teens",
     "TV-MA":"Adults","R":"Adults","NC-17":"Adults"}
df["rating_group"] = df["rating"].map(m)
print(df["rating_group"].value_counts(dropna=False))

rating_group
Adults    4009
Teens     3800
Kids       908
NaN         90
Name: count, dtype: int64

In [14]:
genres = (df[["show_id", "listed_in"]]
          .assign(genre=df["listed_in"].str.split(", "))
          .explode("genre")[["show_id", "genre"]])

countries = (df.loc[df["country"] != "Unknown", ["show_id", "country"]]
             .assign(country=lambda d: d["country"].str.split(", "))
             .explode("country"))

In [15]:
print(df.shape)                       # (8807, 28)
print(df.isna().sum()[lambda s: s > 0])
assert df["show_id"].is_unique
assert genres["genre"].str.strip().ne("").all()

import os; os.makedirs("data/clean", exist_ok=True)
df.to_csv("data/clean/titles_clean.csv", index=False)
genres.to_csv("data/clean/genres.csv", index=False)
countries.to_csv("data/clean/countries.csv", index=False)

(8807, 28)
date_added            10
rating                 7
year_added            10
month_added           10
runtime_min         2676
n_seasons           6131
years_to_netflix      10
rating_group          90
dtype: int64

## Content‑Based “Because You Watched…” Recommender

#### Step 1 — Imports & Load Cleaned Data

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MultiLabelBinarizer, OneHotEncoder, StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors

df = pd.read_csv("data/clean/titles_clean.csv")

#### Step 2 — TF‑IDF Vectorization of Description
This captures semantic meaning of each title.

In [17]:
tfidf = TfidfVectorizer(stop_words="english", max_features=5000)
tfidf_matrix = tfidf.fit_transform(df["description"])

#### Step 3 — Encode Genres, Country, Rating Group
Genres → Multi‑Hot Encoding

In [19]:
df["genre_list"] = df["listed_in"].str.split(", ")

mlb = MultiLabelBinarizer()
genre_matrix = mlb.fit_transform(df["genre_list"])

Primary Country → One‑Hot

In [20]:
ohe_country = OneHotEncoder(sparse_output=False)
country_matrix = ohe_country.fit_transform(df[["primary_country"]])

Rating Group → One‑Hot

In [21]:
ohe_rating = OneHotEncoder(sparse_output=False)
rating_matrix = ohe_rating.fit_transform(df[["rating_group"]].fillna("Unknown"))

#### Step 4 — Numeric Features

In [22]:
numeric_features = df[[
    "runtime_min",
    "n_seasons",
    "cast_size",
    "description_length",
    "n_genres"
]].fillna(0)

scaler = StandardScaler()
numeric_matrix = scaler.fit_transform(numeric_features)

#### Step 5 — Combine All Features Into One Matrix
This is our full content embedding for each title.

In [27]:
from scipy.sparse import hstack

feature_matrix = hstack([
    tfidf_matrix,
    genre_matrix,
    country_matrix,
    rating_matrix,
    numeric_matrix
])
feature_matrix = feature_matrix.tocsr()

#### Step 6 — Build Similarity Engine
We use Nearest Neighbors (KNN) with cosine similarity.

In [24]:
nn = NearestNeighbors(metric="cosine", algorithm="brute")
nn.fit(feature_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

#### Step 7 — Recommendation Function

In [25]:
def recommend(title, n=10):
    if title not in df["title"].values:
        return f"Title '{title}' not found in dataset."

    idx = df.index[df["title"] == title][0]
    distances, indices = nn.kneighbors(feature_matrix[idx], n_neighbors=n+1)

    results = []
    for dist, i in zip(distances[0][1:], indices[0][1:]):
        results.append((df.loc[i, "title"], 1 - dist))

    return results

#### Let's try it now

In [28]:
recommend("Kota Factory", n=5)

[('Bhaag Beanie Bhaag', np.float64(0.8592944193816295)),
 ('Taj Mahal 1989', np.float64(0.8332860365336167)),
 ('Mismatched', np.float64(0.8291950185658856)),
 ('Little Things', np.float64(0.8133347357566494)),
 ('Home for Christmas', np.float64(0.8066044864787447))]

This system looks at what Kota Factory is about — its themes, genres, cast size, country, description, and other metadata — and finds other shows that share similar characteristics.

The number next to each show is how similar it is.

For example, Bhaag Beanie Bhaag has a similarity score of 0.859, meaning it’s very close to Kota Factory in terms of content style.

In [29]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,runtime_min,n_seasons,years_to_netflix,n_genres,n_countries,cast_size,description_length,primary_country,rating_group,genre_list
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,...,90.0,NaN,1.0,1,1,0,27,United States,Teens,[Documentaries]
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,...,NaN,2.0,0.0,3,1,19,27,South Africa,Adults,"[International TV Shows, TV Dramas, TV Mysteries]"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,...,NaN,1.0,0.0,3,0,9,27,Unknown,Adults,"[Crime TV Shows, International TV Shows, TV Ac..."
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,...,NaN,1.0,0.0,2,0,0,24,Unknown,Adults,"[Docuseries, Reality TV]"
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,...,NaN,2.0,0.0,3,1,8,24,India,Adults,"[International TV Shows, Romantic TV Shows, TV..."

In [30]:
recommend("Ganglands",n=3)

[('Fatal Destiny', np.float64(0.8245582106242563)),
 ('Triad Princess', np.float64(0.8150067642039027)),
 ('Answer for Heaven', np.float64(0.8106272106683008))]

In [31]:
recommend("Fatal Destiny",n=3)

[('Ganglands', np.float64(0.8245582106242563)),
 ('Smoking', np.float64(0.7755778107326242)),
 ('Dealer', np.float64(0.7700413116647529))]